apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  profile: default
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
