apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crd-istio-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/MarcioCavalante/gitops-test.git
    targetRevision: HEAD
    path: env/production/waves/1/crd-istio-operator
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
