apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-state-metrics
    repoURL: https://prometheus-community.github.io/helm-charts/
    #targetRevision: 3.5.0
