apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-example
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MarcioCavalante/bookinfo-example.git
    targetRevision: HEAD
    path: /
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
