apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
  selector:
    app.kubernetes.io/name: argocd-server
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway-nodeport
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30002
  selector:
    app: istio-ingressgateway
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-nginx-ingress-nodeport
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30003
  selector:
    app: nginx-ingress-nginx-ingress
  type: NodePort
