apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/istio/istio.git
    targetRevision: HEAD
    path: manifests/charts/istio-operator
    helm:
      parameters:
        - name: operatorNamespace
          value: "istio-operator"
        - name: watchedNamespaces
          value: "istio-system"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
