apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/MarcioCavalante/gitops-test.git
    targetRevision: HEAD
    path: files/helm-charts/helm-istio-operator/istio-1.11.1/manifests/charts/
    helm:
      parameters:
        - name: watchedNamespaces
          value: "istio-system"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
